#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# RETRIEVE ARGUMENTS FROM THE MANIFEST
#=================================================

site_name=$YNH_APP_ARG_SITE_NAME
site_owner=$YNH_APP_ARG_SITE_OWNER
site_owner_url=$YNH_APP_ARG_SITE_OWNER_URL
randomstring=$(ynh_string_random --length=12)

#=================================================
# STORE SETTINGS FROM MANIFEST
#=================================================

ynh_app_setting_set --key=site_name --value=$site_name
ynh_app_setting_set --key=site_owner --value=$site_owner
ynh_app_setting_set --key=site_owner_url --value=$site_owner_url
ynh_app_setting_set --key=randomstring --value=$randomstring

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

ynh_setup_source --dest_dir="$install_dir/build"

#=================================================
# BUILDING SOURCES AND SETTING UP THE SERVER
#=================================================
ynh_script_progression "Building the sources (it will take some time)..."

ynh_go_install

pushd "$install_dir/build"
	# Build the sources

	export GOPATH="$install_dir/build/go"
	export GOCACHE="$install_dir/build/.cache"
	CGO_ENABLED=1 go build -trimpath -v -o "$install_dir/bin/" > /dev/null 2>&1
popd

ynh_safe_rm "$install_dir/build"
ynh_go_remove

# Set permissions to app files
chown -R $app:root "$install_dir"
chmod 750 "${install_dir}/bin/satdress"

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

ynh_config_add_nginx

ynh_config_add_systemd

ynh_config_add_logrotate

yunohost service add $app --description="Federated Lightning addresses server" --log="/var/log/$app/$app.log"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service=$app --action="start"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
