#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# RETRIEVE ARGUMENTS FROM THE MANIFEST
#=================================================

site_name=$YNH_APP_ARG_SITE_NAME
site_owner=$YNH_APP_ARG_SITE_OWNER
site_owner_url=$YNH_APP_ARG_SITE_OWNER_URL
randomstring=$(ynh_string_random --length=12)

#=================================================
# STORE SETTINGS FROM MANIFEST
#=================================================

ynh_app_setting_set --key=site_name --value=$site_name
ynh_app_setting_set --key=site_owner --value=$site_owner
ynh_app_setting_set --key=site_owner_url --value=$site_owner_url
ynh_app_setting_set --key=randomstring --value=$randomstring

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

# Download, check integrity, uncompress and patch the source from app.src
ynh_setup_source --dest_dir="$install_dir/build"

#REMOVEME? Assuming the install dir is setup using ynh_setup_source, the proper chmod/chowns are now already applied and it shouldn't be necessary to tweak perms | chmod -R o-rwx "$install_dir"
#REMOVEME? Assuming the install dir is setup using ynh_setup_source, the proper chmod/chowns are now already applied and it shouldn't be necessary to tweak perms | chown -R $app:www-data "$install_dir"
#=================================================
# SPECIFIC SETUP
#=================================================
# BUILDING SOURCES AND SETTING UP THE SERVER
#=================================================
ynh_script_progression "Building the sources (it will take some time)..."

ynh_go_install

pushd "$install_dir/build"
	# Build the sources

	export GOPATH="$install_dir/build/go"
	export GOCACHE="$install_dir/build/.cache"
	CGO_ENABLED=1 go build -trimpath -v -o "$install_dir/bin/" > /dev/null 2>&1
popd

#REMOVEME? ynh_safe_rm "$install_dir/build"
ynh_go_remove

# Set permissions to app files
#REMOVEME? Assuming the install dir is setup using ynh_setup_source, the proper chmod/chowns are now already applied and it shouldn't be necessary to tweak perms | chown -R $app:root "$install_dir"
chmod 750 "${install_dir}/bin/satdress"

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

# Create a dedicated NGINX config
ynh_config_add_nginx

# Create a dedicated systemd config
ynh_config_add_systemd

ynh_config_add_logrotate

yunohost service add $app --description="Federated Lightning addresses server" --log="/var/log/$app/$app.log"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

# Start a systemd service
ynh_systemctl --service=$app --action="start"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
